MessengerClientDB/Models/Messages.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessengerClientDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int ID { get; set; }
        public string SenderID { get; set; }
        public string ReceiverID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Contents { get; set; }
        public string Read { get; set; }
        public Nullable<bool> Queued { get; set; }
    }
}

MessengerClientDB/Models/ViewModels/MessagesViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MessengerClientDB.Models.ViewModels
{
    public class MessageVM
    {
        public int ID { get; set; }
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 4)]
        public string SenderID { get; set; }

        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 4)]
        public string ReceiverID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date { get; set; }

        [DataType(DataType.Time)]
        public Nullable<System.TimeSpan> Time { get; set; }

        [StringLength(1000)]
        public string Contents { get; set; }

        [StringLength(6)]
        public string Read { get; set; }

        public Nullable<bool> Queued { get; set; }
    }

    public class MessageReadVM : MessageVM
    {
        [Display(Name = "Change to Read/Unread")]
        public bool IsRead { get; set; }
    }

    public class SendMessageVM
    {
        public int ID { get; set; }
        public string SenderID { get; set; }
        [Display(Name = "To:")]
        public string ReceiverID { get; set; }
        public string Contents { get; set; }
        [Display(Name = "Message")]
        public string MyContents { get; set; }
    }

    public class QueueDeleteMsgVM : MessageVM
    {
        [Display(Name = "Saved in Inbox")]
        public bool Inbox { get; set; }
    }

    public class QueueDeleteVM
    {
        public string Sender { get; set; }
        [Display(Name = "Saved in Inbox")]
        public List<QueueDeleteMsgVM> InInbox { get; set; }

        public QueueDeleteVM()
        {
            InInbox = new List<QueueDeleteMsgVM>();
        }
    }

    internal class MessageComparer : IEqualityComparer<Messages>
    {
        public bool Equals(Messages x, Messages y)
        {
            if (string.Equals(x.ReceiverID, y.ReceiverID) && string.Equals(x.SenderID, y.SenderID) && string.Equals(x.Contents, y.Contents) && string.Equals(x.Date, y.Date) && string.Equals(x.Time, y.Time))
            {
                return true;
            }
            return false;
        }

        public int GetHashCode(Messages obj)
        {
            string myHashInfo = obj.ReceiverID + obj.SenderID + obj.Contents + obj.Date + obj.Time;
            return myHashInfo.GetHashCode();
        }
    }
}

MessengerClientDB/Controllers/MessagesController.cs
using MessengerClientDB.Models;
using MessengerClientDB.Models.ViewModels;
using MessengerClientDB.Restful;
using MessengerClientDB.Unit;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MessengerClientDB.Controllers
{
    public class MessagesController : Controller
    {
        private IUnitOfWork _unitOfWork;

        private IMessagesRest _messageRest;


        public MessagesController(IMessagesRest messageRest)

        {
            _unitOfWork = new UnitOfWork();
            _messageRest = messageRest;
        }

        // Displays the received messages. 
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> Inbox(string SearchReceiverID)
        {
            string myName = User.Identity.GetUserName();
            var messages = await _unitOfWork.messagesRepo.GetInboxAsync(myName);
            if (!string.IsNullOrEmpty(SearchReceiverID))
            {
                messages = messages.Where(s => s.SenderID.Contains(SearchReceiverID)).OrderByDescending(s => s.Date).ThenByDescending(s => s.Time);
            }
            List<MessageVM> messagesVM = new List<MessageVM>();
            foreach (Messages msg in messages)
            {
                MessageVM msgVM = CreateMsgVM(msg);
                msgVM.ID = msg.ID;
                messagesVM.Add(msgVM);
            }
            return View(messagesVM);
        }

        // Displays all the sent messages. 
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> Sent(string SearchReceiverID)
        {
            string myName = User.Identity.GetUserName();
            var messages = await _unitOfWork.messagesRepo.GetSentAsync(myName);
            if (!string.IsNullOrEmpty(SearchReceiverID))
            {
                messages = messages.Where(s => s.ReceiverID.Contains(SearchReceiverID)).OrderByDescending(s => s.Date).ThenByDescending(s => s.Time);
            }
            List<MessageVM> messagesVM = new List<MessageVM>();
            foreach (Messages msg in messages)
            {
                MessageVM msgVM = CreateMsgVM(msg);
                msgVM.ID = msg.ID;
                messagesVM.Add(msgVM);
            }
            return View(messagesVM);
        }

        // Displays a message.
        // GET: Messages/Details/5
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> Read(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Messages message = await _unitOfWork.messagesRepo.GetAsync((int)id);
            if (message == null)
            {
                return HttpNotFound();
            }
            MessageReadVM model = new MessageReadVM
            {
                ID = message.ID,
                SenderID = message.SenderID,
                ReceiverID = message.ReceiverID,
                Date = message.Date,
                Time = message.Time,
                Contents = message.Contents,
                Read = message.Read,
                Queued = message.Queued,
                IsRead = false
            };
            return View(model);
        }

        // Saves the changes made to a messages read value. 
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> Read([Bind(Include = "ID,IsRead")] MessageReadVM model)
        {
            if (model == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Messages message = await _unitOfWork.messagesRepo.GetAsync(model.ID);
            if (message == null)
            {
                return HttpNotFound();
            }
            if (model.IsRead)
            {
                message.Read = "Read";
            }
            else
            {
                message.Read = "Unread";
            }
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Inbox");
        }

        // Gets a message that is to be saved on the service's database & that is to be stored on the client's database. 

        // Get: Messages/SendMessage
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> SendMessage(int? id)
        {
            SendMessageVM reply = new SendMessageVM();
            string myName = User.Identity.GetUserName();
            if (id == null)
            {
                reply.Contents = null;
                return View(reply);
            }
            Messages message = await _unitOfWork.messagesRepo.GetAsync((int)id);
            if (message == null)
            {
                return HttpNotFound();
            }
            reply.ReceiverID = message.ReceiverID == myName ? message.SenderID : message.ReceiverID;
            reply.ID = message.ID;
            reply.Contents = message.Contents;
            return View(reply);
        }

        // Sends a message to be saved on the service's database & also stores the message on the client's database. 
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> SendMessage([Bind(Include = "ID,ReceiverID,MyContents")] SendMessageVM message)
        {
            if (!ModelState.IsValid)
            {
                return View(message);
            }
            Users user = await _unitOfWork.usersRolesRepo.GetAsync(message.ReceiverID);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "User does not exist.");
                return View(message);
            }
            string myName = User.Identity.GetUserName();
            Messages myMessage = CreateMessage(myName, message.ReceiverID, message.MyContents);
            bool response = await _messageRest.SendAsync(myMessage);
            if (response)
            {
                _unitOfWork.messagesRepo.Add(myMessage);
                await _unitOfWork.SaveAsync();
                return RedirectToAction("Inbox");
            }
            return View(myMessage);
        }

        // Gets & displays messages that are stored on the service's database. 
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> Dequeue(int? id)
        {
            List<Messages> messages = await _messageRest.DequeueAsync(User.Identity.GetUserName());
            List<MessageVM> messagesVM = new List<MessageVM>();
            foreach (Messages msg in messages)
            {
                messagesVM.Add(CreateMsgVM(msg));
            }
            TempData["messagesVM"] = messagesVM;
            return View(messagesVM);
        }

        // Saves messages from the service's database on the client's database. 
        [HttpPost]
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> Dequeue()
        {
            if (TempData["messagesVM"] == null)
            {
                return RedirectToAction("Inbox");
            }
            List<MessageVM> messagesVM = (List<MessageVM>)TempData["messagesVM"];
            List<Messages> messages = new List<Messages>();
            foreach (var message in messagesVM)
            {
                messages.Add(new Messages
                {
                    SenderID = message.SenderID,
                    ReceiverID = message.ReceiverID,
                    Date = message.Date,
                    Time = message.Time,
                    Contents = message.Contents,
                    Read = message.Read,
                    Queued = message.Queued
                });
            }
            _unitOfWork.messagesRepo.AddRange(messages);
            await _unitOfWork.SaveAsync();
            return RedirectToAction("Inbox");
        }

        // Get method to delete messages stored on the service database. 
        // GET: Messages/Delete/5
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> QueueDelete()
        {
            string myName = User.Identity.GetUserName();
            List<Messages> msgsQueued = await _messageRest.DequeueAsync(myName);
            var inbox = await _unitOfWork.messagesRepo.GetInboxAsync(myName);
            QueueDeleteVM queueVM = new QueueDeleteVM();
            foreach (Messages msg in msgsQueued)
            {
                QueueDeleteMsgVM msgVM = CreateQueueDeleteMsgVM(msg, inbox);
                queueVM.InInbox.Add(msgVM);
            }
            return View(queueVM);
        }

        // Deletes messages stored on the service database. 
        // POST: Messages/GetSent
        [ValidateAntiForgeryToken]
        [HttpPost]
        [Authorize(Roles = "Admin,User")]
        public async Task<ActionResult> QueueDelete([Bind(Include = "Sender")]QueueDeleteVM model)
        {
            Users user = await _unitOfWork.usersRolesRepo.GetAsync(model.Sender);
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "User does not exist.");
                return View(model);
            }
            List<MessageVM> msgsDelete = new List<MessageVM>();
            string sender = model.Sender;
            string myName = User.Identity.GetUserName();
            string deleteCount = "0";
            if (!String.IsNullOrEmpty(sender) && !String.IsNullOrWhiteSpace(sender))
            {

MessengerClientDB/Views/Messages/Delete.cshtml
@model MessengerClientDB.Models.ViewModels.MessageVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h5>Deletes message from client database.</h5>
<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.SenderID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReceiverID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiverID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Read)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Read)
        </dd>
    </dl>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    </div>
}
<p>
    @Html.ActionLink("Reply", "SendMessage", new { id = Model.ID }) |
    @Html.ActionLink("Inbox", "Inbox", "Messages") |
    @Html.ActionLink("Sent", "Sent", "Messages")
</p>

MessengerClientDB/Views/Messages/Dequeue.cshtml
@model IEnumerable<MessengerClientDB.Models.ViewModels.MessageVM>

@{
    ViewBag.Title = "Dequeue";
}

<h2>Dequeue</h2>

<h5>Displays messages that are stored in the service database. Press save to save them to the client database. Note duplicate messages are not saved.</h5>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Save" class="btn btn-default" />
    </div>
<h5> </h5>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SenderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReceiverID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contents)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Read)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SenderID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReceiverID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contents)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Read)
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Inbox", "Inbox", "Messages") |
    @Html.ActionLink("Sent", "Sent", "Messages")
</div>

MessengerClientDB/Views/Messages/Inbox.cshtml
@model IEnumerable<MessengerClientDB.Models.ViewModels.MessageVM>

@{
    ViewBag.Title = "Inbox";
}

<h2>Inbox</h2>

<p>
    @Html.ActionLink("Send Message", "SendMessage", "Messages") |
    @Html.ActionLink("Delete Queue", "QueueDelete", "Messages") |
    @Html.ActionLink("Dequeue Messages", "Dequeue", "Messages")
</p>

@using (Html.BeginForm("Inbox", "Messages", FormMethod.Get))
{
    <p>
        Receiver: @Html.TextBox("SearchReceiverID")
        <input type="submit" value="Filter" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SenderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReceiverID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contents)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Read)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SenderID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReceiverID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contents)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Read)
            </td>
            <td>
                @Html.ActionLink("Reply", "SendMessage", new { id = item.ID }) |
                @Html.ActionLink("Read", "Read", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Sent", "Sent", "Messages")
</p>

MessengerClientDB/Views/Messages/QueueDelete.cshtml
@model MessengerClientDB.Models.ViewModels.QueueDeleteVM

@{

    ViewBag.Title = "QueueDelete";
}
<h2>Queue Delete</h2>

<h5>Deletes messages that are stored in the service database.</h5>


@using (Html.BeginForm("QueueDelete", "Messages", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Sender, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Sender, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Sender, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            @ViewBag.DeleteCount
        </div>
    </div>
</div>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.InInbox.First().SenderID)
        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.InInbox.First().ReceiverID)
        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.InInbox.First().Date)
        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.InInbox.First().Time)
        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.InInbox.First().Contents)
        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.InInbox.First().Read)
        </th>
        <th>
            @Html.DisplayNameFor(modelItem => modelItem.InInbox.First().Inbox)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.InInbox)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SenderID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReceiverID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contents)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Read)
        </td>
        <td>
            @if (item.Inbox)
            {
                <h5>yes</h5>
            }
            else
            {
                <h5>no</h5>
            }
        </td>
    </tr>
    }

</table>
<p>
    @Html.ActionLink("Inbox", "Inbox", "Messages") |
    @Html.ActionLink("Sent", "Sent", "Messages")
</p>

MessengerClientDB/Views/Messages/Read.cshtml
@model MessengerClientDB.Models.ViewModels.MessageReadVM

@{
    ViewBag.Title = "Read";
}

<h2>Read</h2>

<div>
    <h5>Mark the message as read/unread.</h5>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SenderID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SenderID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReceiverID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReceiverID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Read)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Read)
        </dd>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <dt>
                @Html.DisplayNameFor(model => model.IsRead)
            </dt>
            <dd>
                @Html.CheckBoxFor(model => model.IsRead)
            </dd>
            <div class="form-group">
                <h2/>
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Update" class="btn btn-default" />
                </div>
            </div>
        }
    </dl>

</div>
<p>
    @Html.ActionLink("Reply", "SendMessage", new { id = Model.ID }) |
    @Html.ActionLink("Inbox", "Inbox", "Messages") |
    @Html.ActionLink("Sent", "Sent", "Messages")
</p>

MessengerClientDB/Views/Messages/SendMessage.cshtml
@model MessengerClientDB.Models.ViewModels.SendMessageVM

@{
    ViewBag.Title = "SendMessage";
}

<h2>Send Message</h2>

<h5>One version of the message is stored in the client database & the other version is stored in the service database. The one stored in the client database belongs to the sender. The one stored in the service database belongs to the receiver.</h5>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.ReceiverID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReceiverID, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReceiverID, "", new { @class = "text-danger" })
        </div>
    </div>

    @if (@Model.Contents != null)
    {
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.DisplayFor(model => model.Contents)
            </div>
        </div>
    }

    <div class="form-group">
        @Html.Label("MyContents", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MyContents, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MyContents, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Send" class="btn btn-default" />
        </div>
    </div>
</div>

}
<p>
    @Html.ActionLink("Inbox", "Inbox", "Messages") |
    @Html.ActionLink("Sent", "Sent", "Messages")
</p>

MessengerClientDB/Views/Messages/Sent.cshtml
@model IEnumerable<MessengerClientDB.Models.ViewModels.MessageVM>

@{
    ViewBag.Title = "Sent";
}

<h2>Sent</h2>

<p>
    @Html.ActionLink("Send Message", "SendMessage", "Messages") |
    @Html.ActionLink("Delete Queue", "QueueDelete", "Messages") |
    @Html.ActionLink("Dequeue Messages", "Dequeue", "Messages")

</p>

@using (Html.BeginForm("Sent", "Messages", FormMethod.Get))
{
    <p>
        Receiver: @Html.TextBox("SearchReceiverID")
        <input type="submit" value="Filter" />
    </p>
}


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SenderID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReceiverID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contents)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Read)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SenderID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReceiverID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contents)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Read)
            </td>
            <td>
                @Html.ActionLink("Send Message", "SendMessage", new { id = item.ID }) |
                @Html.ActionLink("Read", "Read", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Inbox", "Inbox", "Messages")
</p>